name: reviewdog
on: pull_request
jobs:
  reviewdog:
    name: reviewdog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - uses: reviewdog/action-rubocop@v2
        with:
          rubocop_version: gemfile
          reporter: github-pr-review
